### ISSUE TITLE
Route to the VPN server via the tunnel

### ISSUE THREAD

**Issue by rojer** [nm-l2tp/network-manager-l2tp#22] opened 2016-10-17 09:53 UTC
I installed the plugin and connection is established, but i end up with a route to the VPN server that points into the tunnel itself:

log:

```
(ppp4)]: Data:   Internal Point-to-Point Address: 89.179.76.176
```

```
$ netstat -nr
...
89.179.76.176   0.0.0.0         255.255.255.255 UH        0 0          0 ppp4
...
```

this obviously does not work, i see no traffic and the tunnel disconnects because of time out after a while.
if i manually remove this rogue route and add a different one, via the "outer" default router, the tunnel works.

**Comment by rojer** [comment] 2016-10-17 11:22
i should note that OS is Ubuntu 16.04 with stock network manager (1.2.2):

```$ dpkg -l | grep network-manager
ii  network-manager                                      1.2.2-0ubuntu0.16.04.3                                      amd64        network management framework (daemon and userspace tools)
```

**Comment by dkosovic** [comment] 2016-10-17 11:34
I'm not sure I understand, I have the same in my log output and netstat -nr output (apart from a different IP address and using ppp0 instead of ppp4).

As it is a direct Point-to-Point connection to 89.179.76.176, no gateway is required, so the gateway is set to 0.0.0.0.

Are you saying the Point-to-Point connection should be using another IP address?

The output of `ip route` is a bit more useful than `netstat -nr` as it also includes the metric. 

The NetworkManager-l2tp code doesn't modify the routing table and leaves it to NetworkManager

**Comment by dkosovic** [comment] 2016-10-17 11:51
Forgot to mention, DNS routing is a common problem with NetworkManager VPN connections. Doing a google search for 'DNS routing ubuntu vpn' comes up with numerous solutions.

**Comment by rojer** [comment] 2016-10-17 11:53
89.179.76.176 is the other end of the tunnel, it cannot possibly be reachable via the tunnel, it's a routing loop.
a packet going elsewhere gets sent to pppX, where it is wrapped into the tunnel headers and is then forwarded to 89.179.76.176, which should be reachable with anything else _but_ the tunnel.

with cable unplugged, my routing table looks like this:

```
$ netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
10.42.0.0       0.0.0.0         255.255.255.0   U         0 0          0 wlan0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
192.168.15.0    0.0.0.0         255.255.255.0   U         0 0          0 vmnet8
192.168.27.0    0.0.0.0         255.255.255.0   U         0 0          0 vmnet1
```

ignore the wifi, docker and vmware interfaces, they're not relevant.

with cable plugged in, i get this:

```
$ netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.190.72.1     0.0.0.0         UG        0 0          0 eth0
10.0.0.0        10.190.72.1     255.0.0.0       UG        0 0          0 eth0
10.42.0.0       0.0.0.0         255.255.255.0   U         0 0          0 wlan0
10.190.72.0     0.0.0.0         255.255.248.0   U         0 0          0 eth0
78.107.31.234   10.190.72.1     255.255.255.255 UGH       0 0          0 eth0
78.107.196.0    10.190.72.1     255.255.252.0   UG        0 0          0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
192.168.15.0    0.0.0.0         255.255.255.0   U         0 0          0 vmnet8
192.168.27.0    0.0.0.0         255.255.255.0   U         0 0          0 vmnet1
```

note the new 10.a.b.c routes - these come via DHCP from the ISP.
vpn host can be resolved, is pingable and can be reached via the default route through 10.190.72.1:

```
$ host vpn.internet.beeline.ru
vpn.internet.beeline.ru has address 89.179.76.179
vpn.internet.beeline.ru has address 89.179.76.176
$ ping vpn.internet.beeline.ru
PING vpn.internet.beeline.ru (89.179.76.179) 56(84) bytes of data.
64 bytes from bras2-loo100.kst.corbina.net (89.179.76.179): icmp_seq=1 ttl=252 time=0.639 ms
64 bytes from bras2-loo100.kst.corbina.net (89.179.76.179): icmp_seq=2 ttl=252 time=0.606 ms
^C
--- vpn.internet.beeline.ru ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.606/0.622/0.639/0.029 ms
```

now, when i first set up the VPN connection, i get this:

```
$ netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         0.0.0.0         0.0.0.0         U         0 0          0 ppp4
0.0.0.0         10.190.72.1     0.0.0.0         UG        0 0          0 eth0
10.0.0.0        10.190.72.1     255.0.0.0       UG        0 0          0 eth0
10.42.0.0       0.0.0.0         255.255.255.0   U         0 0          0 wlan0
10.190.72.0     0.0.0.0         255.255.248.0   U         0 0          0 eth0
78.107.31.234   10.190.72.1     255.255.255.255 UGH       0 0          0 eth0
78.107.196.0    10.190.72.1     255.255.252.0   UG        0 0          0 eth0
89.179.76.179   0.0.0.0         255.255.255.255 UH        0 0          0 ppp4
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
192.168.15.0    0.0.0.0         255.255.255.0   U         0 0          0 vmnet8
192.168.27.0    0.0.0.0         255.255.255.0   U         0 0          0 vmnet1
```

there's a default route via ppp4 (although we still have default via outer gw), but there is also this very specific /32 route to vpn server via the tunnel itself, which does not make sense.
i get no internet connection (can't ping 8.8.8.8) and the gateway itself too:

```
$ ping 89.179.76.179
PING 89.179.76.179 (89.179.76.179) 56(84) bytes of data.
^C
--- 89.179.76.179 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

however, as soon as i remove this route and add my own, it starts working:

```
$ sudo ip route delete 89.179.76.179/32                                                                                                                                                               
$ sudo ip route add 89.179.76.0/24 via 10.190.72.1
$ ping 89.179.76.179
PING 89.179.76.179 (89.179.76.179) 56(84) bytes of data.
64 bytes from 89.179.76.179: icmp_seq=1 ttl=252 time=0.662 ms
64 bytes from 89.179.76.179: icmp_seq=2 ttl=252 time=0.684 ms
```

and internet connection works too (so having two defaults is fine):

```
$ ping 8.8.8.8                                                                                                                                                                                        
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=58 time=8.93 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=58 time=8.34 ms
```

**Comment by rojer** [comment] 2016-10-17 12:04
this is not related to DNS routing, my dns servers as given out by DHCP are (as found in the current lease file):
```
option domain-name-servers 213.234.192.8,85.21.192.3;
```

they are teh esame as given out by the tunnel server:
```
(ppp4)]: Data:   Internal DNS: 213.234.192.7
(ppp4)]: Data:   Internal DNS: 85.21.192.5
```

**Comment by dkosovic** [comment] 2016-10-18 13:07
I also have that very specific /32 route that NetworkManager creates to the VPN server I connect to. The VPN server I connect to also has a specific route back to my client via itself as the gateway, so I am able to ping it.

I can't explain why that specific /32 route gets added, but can understand when it might be needed in some situations with certain settings. It's definitely something NetworkManager does and not in the code from this repo, I definitely see it happen with other NetworkManager VPN plug-ins.

As a workaround, you could specify a metric lower than that very specific /32 route (which I think has a metric of 50) to ensure all traffic going to 89.179.76.0/24 goes via that route. You could add the route either in the GUI IPv4 Settings, Routes for the VPN connection or add a metric argument to the command-line, e.g :

    sudo ip route add 89.179.76.0/24 via 10.190.72.1 metric 20

If you add that route, you might as well in the IPv4 Settings, Routes, tick "Ignore automatically obtained routes" and save the configuration. That way not all of the traffic will go over the VPN connection.

**Comment by rojer** [comment] 2016-10-18 16:06
`VPN server I connect to also has a specific route back to my client via itself as the gateway, so I am able to ping it.` - that actually makes some sense, though strictly speaking route via self would also loop... but i assume it ends up taking the default route or something. but how a specific route _via the tunnel_ can possibly, ever work? i don't get it... i mean, i can work around this via up/down scripts and the rest, but adding route via tunnel seems like a clear bug to me. better do nothing, not add any route, than do _that_.

**Comment by cristobaltapia** [comment] 2016-11-30 23:14
I think that I am having a similar (or the same) issue. My knowledge about routing tables and VPN connections is not very profound, but here is what I get when running ```ip route```:

```
default dev ppp0 proto static scope link metric 50 
default via 192.168.2.1 dev wlp2s0 proto static metric 600 
10.134.0.0 dev ppp0 proto kernel scope link src 10.134.0.2 metric 50 
129.69.159.69 via 192.168.2.1 dev wlp2s0 proto static metric 600 
192.168.2.0/24 dev wlp2s0 proto kernel scope link src 192.168.2.113 metric 302 
192.168.2.0/24 dev wlp2s0 proto kernel scope link src 192.168.2.108 metric 600 
192.168.2.1 dev wlp2s0 proto static scope link metric 600 
```

In another VPN connection (that is working but is not an IPsec one) I get the following:

```
default via 10.4.0.1 dev tun0 proto static metric 50 
default via 192.168.2.1 dev wlp2s0 src 192.168.2.113 metric 302 
10.4.0.0/16 dev tun0 proto kernel scope link src 10.4.78.110 metric 50 
192.168.2.0/24 dev wlp2s0 proto kernel scope link src 192.168.2.113 metric 302 
192.168.2.1 dev wlp2s0 proto static scope link metric 600 
213.152.162.164 via 192.168.2.1 dev wlp2s0 proto static metric 600 
```

**Comment by dkosovic** [comment] 2016-12-03 10:15
NetworkManager is creating a default route with metric of 50 in both cases.
10.134.0.0

The IPsec interface is 229.65.159.79 and is created by strongswan (or libreswan).

The L2TP ppp0 interface is 10.134.0.0 and is created by xl2tpd/pppd.

In your case I have no idea why IPsec is using a multicast IP address, while L2TP is a private IP address.

Addresses starting with a number between 224 and 239 are used for IP multicast and are routed completely differently to unicast addresses.

**Comment by cristobaltapia** [comment] 2016-12-03 10:53
The server address is not actually that one (I changed it in the post to not write the original one... I thought it would be better so). The other addresses are unchanged.

**Comment by cristobaltapia** [comment] 2016-12-03 11:06
I have tried to add the routes manually, but it doesn't work. According to [1] I should only have to do
```
route add -net 10.10.0.0 netmask 255.255.240.0 dev ppp0
```
to be connected to the remote intranet.

[1] http://pptpclient.sourceforge.net/routing.phtml#client-to-lan

**Comment by dkosovic** [comment] 2016-12-03 11:52
I'm still confused, according to the following you have a Point-to-Point connection to 10.134.0.0 :

    10.134.0.0 dev ppp0 proto kernel scope link src 10.134.0.2 metric 50

but Point-to-Point connections are to hosts, not networks (i.e. IP addresses ending in zero) as no routing is involved, it connects directly to the L2TP host.

This is what I have for the L2TP Point-to-Point connection :

    120.102.71.36 dev ppp0  proto kernel  scope link  src 192.168.67.165  metric 50

I might just be misreading your `ip route` output, `netstat -nr` output might help.

**Comment by dkosovic** [comment] 2016-12-03 12:57
Sorry I'm not familiar with the topology of your network, especially since you've listed multiple private networks (e.g. 10.10.0.0  and 10.134.0.0 with a source 10.134.0.2 interface that doesn't exist) it's pretty confusing. Probably simplest to tick "ignore automatically obtained routes" in the VPN's IPv4 GUI route settings and then manually add the required routes. But this also assumes the multiple private networks are accessible to each other.

**Comment by cristobaltapia** [comment] 2016-12-03 13:07
I am not sure either about the topology of the network, but I got those numbers while being at a computer at work. Maybe this can help:

```
~$ netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.10.10.51     0.0.0.0         UG        0 0          0 enp7s0
10.10.0.0       0.0.0.0         255.255.240.0   U         0 0          0 enp7s0
10.132.0.0      10.10.10.100    255.255.240.0   UG        0 0          0 enp7s0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 enp7s0
ctapia@CL0001:~$

~$ ip route
default via 10.10.10.51 dev enp7s0  proto static  metric 100 
10.10.0.0/20 dev enp7s0  proto kernel  scope link  src 10.10.0.130  metric 100 
10.132.0.0/20 via 10.10.10.100 dev enp7s0  proto dhcp  metric 100 
169.254.0.0/16 dev enp7s0  scope link  metric 1000 
```

**Comment by cristobaltapia** [comment] 2016-12-05 07:54
So, if this is a bug, where should I report it? To the NetworkManager Project?

**Comment by dkosovic** [comment] 2016-12-05 14:09
Honestly, I'm not sure where the issue is.

NetworkManager only sets up the default route :

    default dev ppp0 proto static scope link metric 50

the rest of the routing entries are done by xl2tpd and pppd.

Extract from pppd manual :
> When IPCP negotiation is completed successfully, pppd will inform the kernel of the local and remote 
> IP addresses for the ppp interface. This is sufficient to create a host route to the remote end of the 
> link, which will enable the peers to exchange IP packets. 

I don't know why that pppd routing entry is missing for you as you have the following:
   10.134.0.0 dev ppp0 proto kernel scope link src 10.134.0.2 metric 50

I would try replacing 10.134.0.2 with the IP address of the ppp0 interface which you can get with the the following command:

    ifconfig ppp0

If the L2TP/IPsec VPN connection works for you with Windows, I would try manually setting up the same routing table on linux.

**Comment by dkosovic** [comment] 2017-03-29 02:54
I'm going to close this issue as the L2TP/IPsec connection is getting established and because the NetworkManager-l2tp code doesn't modify the routing table and leaves it to NetworkManager to take care of it.

There are heaps of reasons as to why routing could be broken, one example and fix is https://github.com/nm-l2tp/network-manager-l2tp/issues/36#issuecomment-285392405

**Closed by dkosovic** 2017-03-29 02:54 UTC

**Comment by dkosovic** [comment] 2020-09-26 00:17
This issue might have been fixed in issue https://github.com/nm-l2tp/NetworkManager-l2tp/issues/132 with commit https://github.com/nm-l2tp/NetworkManager-l2tp/commit/95fdaa6dc8348ba7f63bcf7aa2ccc95b762c491d
