### ISSUE TITLE
Secret Service issue with qemu-kvm

### ISSUE THREAD

**Issue by krasnog** [nm-l2tp/network-manager-l2tp#2] opened 2016-04-23 18:48 UTC
I used master from this repo. I can't add l2tp connection in the "Edit Connections" dialog.

nm service says "path is not absolute" in logs.

After I added absolute path to plugin entry in /usr/lib/NetworkManager/VPN/nm-l2tp-service.name I was able to add a connection, but wasn't able to edit it. When I press "Edit" nm-l2tp-auth-dialog crashes. Also error dialog appears with title "Error initializing editor" and contents "User canceled the secrets request.

When I try to connect, "Timed out waiting for the service to start" appears, and then:

(NetworkManager:645): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

It's a fresh install in qemu. I'm not sure if I installed all the required packages, but all the packages required for building have been installed.

**Comment by dkosovic** [comment] 2016-04-25 03:48
I've installed Ubuntu 16.04, I'm seeing the following which I think is the cause of the nm-l2tp-auth-dialog crashes :

Apr 25 13:30:31 OptiPlex-7040 gnome-session[1694]: (process:3404): libnm-util-ERROR **: libnm symbols detected; Mixing libnm with libnm-util/libnm-glib is not supported

I've seen fixes for NetworkManager-pptp for that mixing libnm with libnm-util/libnm-glib issue, I'm looking into it.

Along with xl2tpd and strongswan, I installed the following which are the same dependencies as the Xenial Xerus network-manager-pptp package :

sudo apt install \
  intltool \
  network-manager-dev \
  libnm-util-dev \
  libnm-glib-dev \
  libnm-glib-vpn-dev \
  libnm-gtk-dev \
  libnm-dev \
  libnma-dev \
  ppp-dev \
  libdbus-glib-1-dev \
  libsecret-1-dev \
  libgtk-3-dev \
  libglib2.0-dev 

and I configured using:

./configure --prefix=/usr  \
--sysconfdir=/etc --localstatedir=/var \
--libdir=/usr/lib/x86_64-linux-gnu --libexecdir=/usr/lib/x86_64-linux-gnu \
 --with-pppd-plugin-dir=/usr/lib/pppd/2.4.7 --enable-absolute-paths

**Comment by dkosovic** [comment] 2016-04-26 22:12
fixes are now in the master branch, but now there is a strongswan issue to solve :

Apr 27 07:49:01 OptiPlex-7040 kernel: [ 1333.034767] audit: type=1400 audit(1461707341.883:76): apparmor="DENIED" operation="sendmsg" info="Failed name lookup - disconnected path" error=-13 profile="/usr/lib/ipsec/charon" name="run/systemd/journal/dev-log" pid=20125 comm="charon" requested_mask="w" denied_mask="w" fsuid=0 ouid=0

**Comment by krasnog** [comment] 2016-04-27 06:25
I can edit the connection now, but the connection still won't go up. When I start freshly created connection, it says something along the lines "connection failed because no valid vpn secrets" in a notify pop-up. "always ask" password setting doesn't work either. On the second attempt a pop-up says it's failed but no reason given.

In journalctl I see the following:
Apr 27 01:57:01 krasno-Standard-PC-i440FX-PIIX-1996 NetworkManager[617]: <info>  [1461736621.3673] keyfile: add connection /etc/NetworkManager/system-connections/Beeline (c7254b7f-a459-455e-9024-5bf18a01e5d8,"Beeline")
Apr 27 01:57:01 krasno-Standard-PC-i440FX-PIIX-1996 NetworkManager[617]: <info>  [1461736621.3687] audit: op="connection-add" uuid="c7254b7f-a459-455e-9024-5bf18a01e5d8" name="Beeline" pid=1706 uid=1000 result="success"
Apr 27 01:57:17 krasno-Standard-PC-i440FX-PIIX-1996 NetworkManager[617]: <info>  [1461736637.8324] audit: op="connection-activate" uuid="c7254b7f-a459-455e-9024-5bf18a01e5d8" name="Beeline" pid=1501 uid=1000 result="success"
Apr 27 01:57:17 krasno-Standard-PC-i440FX-PIIX-1996 NetworkManager[617]: <info>  [1461736637.8542] vpn-connection[0x2146200,c7254b7f-a459-455e-9024-5bf18a01e5d8,"Beeline",0]: Started the VPN service, PID 1805
Apr 27 01:57:17 krasno-Standard-PC-i440FX-PIIX-1996 NetworkManager[617]: <info>  [1461736637.8825] vpn-connection[0x2146200,c7254b7f-a459-455e-9024-5bf18a01e5d8,"Beeline",0]: Saw the service appear; activating connection
Apr 27 01:57:17 krasno-Standard-PC-i440FX-PIIX-1996 NetworkManager[617]: <error> [1461736637.9050] vpn-connection[0x2146200,c7254b7f-a459-455e-9024-5bf18a01e5d8,"Beeline",0]: plugin NeedSecrets request #1 failed: No such interface 'org.freedesktop.NetworkManager.VPN.Plugin' on object at path /org/freedesktop/NetworkManager/VPN/Plugin
Apr 27 01:57:17 krasno-Standard-PC-i440FX-PIIX-1996 NetworkManager[617]: <info>  [1461736637.9076] vpn-connection[0x2146200,c7254b7f-a459-455e-9024-5bf18a01e5d8,"Beeline",0]: VPN plugin: state changed: init (1)

and probably from second attempt:

vpn-connection[0x21463f0,c7254b7f-a459-455e-9024-5bf18a01e5d8,"Beeline",0]: Saw the service appear; activating connection
Apr 27 01:58:00 krasno-Standard-PC-i440FX-PIIX-1996 gnome-session[1322]: Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Apr 27 01:58:06 krasno-Standard-PC-i440FX-PIIX-1996 NetworkManager[617]: <info>  [1461736686.0303] keyfile: update /etc/NetworkManager/system-connections/Beeline (c7254b7f-a459-455e-9024-5bf18a01e5d8,"Beeline")
Apr 27 01:58:06 krasno-Standard-PC-i440FX-PIIX-1996 NetworkManager[617]: <info>  [1461736686.0384] vpn-connection[0x21463f0,c7254b7f-a459-455e-9024-5bf18a01e5d8,"Beeline",0]: VPN connection: (ConnectInteractive) reply received
Apr 27 01:58:06 krasno-Standard-PC-i440FX-PIIX-1996 NetworkManager[617]: <info>  [1461736686.0474] vpn-connection[0x21463f0,c7254b7f-a459-455e-9024-5bf18a01e5d8,"Beeline",0]: VPN service disappeared
Apr 27 01:58:06 krasno-Standard-PC-i440FX-PIIX-1996 NetworkManager[617]: <warn>  [1461736686.0533] vpn-connection[0x21463f0,c7254b7f-a459-455e-9024-5bf18a01e5d8,"Beeline",0]: VPN connection: failed to connect: 'Message recipient disconnected from message bus without replying'

in particular:

9024-5bf18a01e5d8,"Beeline",0]: plugin NeedSecrets request #1 failed: No such interface 'org.freedesktop.NetworkManager.VPN.Plugin' on object at path /org/freedesktop/NetworkManager/VPN/Plugin

**Comment by dkosovic** [comment] 2016-04-27 07:43
I was seeing "connection failed because no valid vpn secrets" initially, but haven't seen it since the recent two commits.

Can you confirm you re-ran ./autogen.sh before the configure ? The proxy in the auth-dialog folder won't get built properly otherwise. 

I removed the VPN connection and re-added it. 

I also did a make clean, just in case some of the D-Bus generated files weren't getting recreated.

**Comment by krasnog** [comment] 2016-04-27 08:27
>Can you confirm you re-ran ./autogen.sh before the configure ?

Yes I cloned it fresh. To verify the error, I just installed a fresh Ubuntu in qemu, installed packages, and compiled the plugin, and it still prints this error.

btw you've missed libtool package from "sudo apt install"

**Comment by dkosovic** [comment] 2016-04-27 11:29
I'll try and reproduce on another computer and get back to you. I got past the AppArmor issue with strongswan by disabling AppArmor.  I now get the following xl2tpd error :

xl2tpd[3731]: Maximum retries exceeded for tunnel 63945.  Closing.

Regarding the dependencies, extract from Ubuntu 16.04's network-manager-pptp-1.1.93 debian/control file :
Build-Depends: debhelper (>= 9),
               dh-autoreconf,
               intltool,
               network-manager-dev (>= 1.1.0),
               libnm-util-dev (>= 1.1.0),
               libnm-glib-dev (>= 1.1.0),
               libnm-glib-vpn-dev (>= 1.1.0),
               libnm-gtk-dev (>= 1.1.0),
               libnm-dev (>= 1.1.0),
               libnma-dev (>= 1.1.0),
               ppp-dev (>= 2.4.7-1+1),
               libdbus-glib-1-dev (>= 0.74),
               libsecret-1-dev,
               libgtk-3-dev (>= 3.4),
               libglib2.0-dev (>= 2.32)

That's what I based my list on, but ignored debhelper and dh-autoreconf, and included xl2tpd and strongswan. The developer packages like libtool, automake, gcc, etc, I think are considered mandatory for building .deb packages, so don't have explicit dependencies in the above.

**Comment by krasnog** [comment] 2016-04-27 13:27
>The developer packages like libtool, automake, gcc, etc, I think are considered mandatory for building .deb packages, so don't have explicit dependencies in the above.

I meant, it would be a good idea to have all needed packages mentioned in the instructions, so that users could just mindlessly Ctrl-V the commands on the fresh install. I'm not building deb packages btw, we are "make installing" it.

I rechecked, by mistakenly assuming xl2tpd was included in the apt install command I forgot to install it on the fresh install.(was installed previous times) Installing it didn't help the "vpn secrets" error though.

**Comment by krasnog** [comment] 2016-04-27 13:39
I have suspicions that lack of entroy in qemu might affect secret encryption somehow. I hope the fact that I test it in qemu doesn't affect the end result. I managed to configure the network without nm plugin. With just xl2tpd and ppp, and it works fine from under qemu.

**Comment by dkosovic** [comment] 2016-04-27 22:34
I think the bug has something to do with the password widget secret in properties/nm-l2tp.c and not having been updated to use libnma. This is just my initial impression after comparing properties/nm-l2tp.c with NetworkManager-pptp's properties/nm-pptp.c and properties/Makefile.am.

I suspect for some reason I'm not triggering the bug, possibly because when I test I'm somehow interact with the GUI differently.

I did a test on Fedora 24 (pre-alpha release) which is NetworkManager 1.2 based and was able to establish a L2TP/IPSec VPN connection no problem. Was hoping I might have been able to trigger the bug there.

The NetworkManager-pptp password widget is a fair bit newer and has a significant number of changes, I'll try and incorporate them.

**Comment by krasnog** [comment] 2016-04-28 07:27
>I suspect for some reason I'm not triggering the bug, possibly because when I test I'm somehow interact with the GUI differently.

I click "Edit Connections" > "Add"> L2TP > Fill Gateway and User Name, Password if I test "Saved" mode, "Always Ask" if don't. > Save > Close > Click at the network manager Icon at the top unity panel > VPN Connections > Click Name of the connection. 

And that's all that's required for my connection.

>I suspect for some reason I'm not triggering the bug

Have you tried to make a fresh install in qemu-kvm (it's pretty quick with proper cpu support) ? If you create a precise list of instructions for a fresh install that works for you, It will be easier to deal with this bug I think. I still think I have missed something. For example trying to make it work again, viewing logs, I found that I forgot to "systemctl disable xl2tpd" this time. It didn't help the secrets issue of course.

**Comment by dkosovic** [comment] 2016-04-28 12:32
Sorry I didn't get a chance to try qemu-kvm or look at the code much.

But I now think it's failing for you where it's trying to pass the secret to the following pppd plug-in:
   /usr/lib/pppd/2.4.7/nm-l2tp-pppd-plugin.so
which is further than I get as I hit an issue with xltpd and the IPSec kernel module, something about protocol 30 not available. On Ubuntu I think I need to pass more xltpd options when IPSec is used. On Fedora the options are on by default.

**Comment by dkosovic** [comment] 2016-05-02 10:45
I've committed a number of significant changes to the master branch, especially src/nm-l2tp-service.c and the properties folder. Hopefully it fixes your credential secrets issue. You may need to delete and re-add the existing VPN connection.

The code is tracking NetworkManger-pptp much more closely.

Regarding the dependencies, instead I would prefer to submit a package to Debian which would then make it to derivatives like Ubuntu. I'm not an Ubuntu (nor Debian) user, so not in the position to maintain the package dependency list for various versions of Ubuntu, especially now in the transition to NetworkManager 1.2.

Ubuntu 16.04 IPSec doesn't come with a SAref patched kernel for the KLIPS kernel module, so IPSec SAref doesn't work with xl2tpd. I also tried user-space xl2tpd, but without luck. Still looking into it.

Hopefully L2TP will now work for you, I wasn't able to test as the VPN server I'm using is L2TP/IPsec.

**Comment by krasnog** [comment] 2016-05-02 15:59
>Hopefully it fixes your credential secrets issue.

Unfortunately this isn't the case. Tested on a fresh ubuntu install.

**Comment by krasnog** [comment] 2016-05-02 17:58
UPD:
I tested "Always ask" mode. The first time I click on the connection it shows the secrets error in a notification popup, and then nothing. When I click _the second_ time it shows a password dialog. I entered my connection's pasword, and it finally connected, showed "vpn connection successfully established" popup. And it worked from the second try (there is an unreported bug when a route for vpn server via default gateway is not created sometimes. Probably has something to do with my vpn server that has load balancer dns that resolves different ips every time)

After this success I tried to click the second time, in the stored secrets mode. It worked.

So it works but the secrets error on the first try is still here. Previously it didn't work even on the second attempt.

**Comment by dkosovic** [comment] 2016-05-03 07:24
Regarding load balancer DNS, extracted comment from lookup_gateway() function in src/nm-l2tp-service.c :

	/* If the hostname resolves to multiple IP addresses, use the first one.
	 * FIXME: maybe we just want to use a random one instead?
	 */

it then uses the IP address with the xl2tpd and strongswan temp config files. The 'nodefaultroute' option is specified in a xl2tpd temp config file. I believe NetworkManager is supposed to take care of the routing, but will look into it further.

Ubuntu 16.04 bolted a bit early with NetworkManager 1.2 which hasn't been released yet, so is using a version from the 1.1.x developer branch (think it's RC1 or an earlier pre-release package). Hopefully once the network-manager-1.2 package is released, it might fix the routing issue.

I'll do some code reading and compare to the original NetworkManager-pptp code I copied to see if I spot anything regarding the secrets error on first attempt. I'll try and reproduce the issue once I get L2TP/IPsec working on Ubuntu 16.04, I wasn't able to reproduce on Fedora 24 pre-release.

**Comment by krasnog** [comment] 2016-05-03 12:02
I made a little experiment. I tried to create pptp connection to see if I'll experience the secrets issue. I did. I started googling for a reason and found that disabling PAP authentification in options cures it. I disabled everything but CHAP and it cured it. I need only CHAP authentification for my server, but leaving all other options in place in Ubuntu 14.04 wasn't an issue. I also tested the creation of CHAP only l2tp connection before for this bug, and the secrets issue was still there, and it doesn't cure it now.

**Comment by krasnog** [comment] 2016-05-03 12:59
Disregard the previous post please. I have secrets issue with "papless" pptp too. I begin to suspect it's qemu related somehow.

**Comment by krasnog** [comment] 2016-05-03 13:39
I tested it more, and discovered that pptp connection will encounter secrets issue probabalistically. I would say there is 15% chance to start a connection without "no valid vpn secrets" right after qemu reboot. Or it's timing related I don't know.

Unrelated issue:I also had an Ubuntu dialog that informed me of a segfault, I had it on the previous fresh ubuntu install too. I ignored it because I thought it's not plugin related issue. I decided to look what is it that crashes, and it turned out it's xl2tpd -D with NetworkManager related arguments. Why it starts during the boot process I don't know. I removed the all l2tp connections from the networknanager and the dialog won't show anymore after reboot. I failed to reproduce it.

**Comment by krasnog** [comment] 2016-05-03 13:43
I think you should wait for someone else to corroborate the secrets issue before spending any more time on it.

**Comment by dkosovic** [comment] 2016-05-03 13:49
No worries, thanks for your efforts! It's good to know you are able to reproduce the issue occasionally with the network-manager-pptp package.

I haven't been able to reproduce, although I'm running on real hardware, not qemu. I also had to hack the network-manager-pptp source code to change the default MTU from 1400 to 1200 to get a connection. I vaguely remember seeing the secrets issue before that. 

With PPTP, I have to enable Point-to-Point Encryption (MPPE) which disables every authentication method except MSCHAP and MSCHAPv2. For L2TP I have been disabling everything except for MSCHAPv2 out of habit.

**Comment by krasnog** [comment] 2016-05-03 13:51
I also want to mention that I checked 14.04 with Sergey's old plugin and it worked flawlessly in qemu. I really don't want to do experimenting on my host system...

**Comment by krasnog** [comment] 2016-05-03 13:54
>reproduce the issue occasionally with the network-manager-pptp package.

to be exact I'm able to reproduce the issue with pptp package most of the time. It's much more commont to encounter the secrets issue after reboot than to see NM trying to connect right away after the first click.

**Comment by dkosovic** [comment] 2016-05-09 13:55
The Ubuntu 16.04 xl2tpd package was built using the output of the following command :
$ dpkg-buildflags --get CFLAGS
-g -O2 -fstack-protector-strong -Wformat -Werror=format-security

Unfortunately the -fstack-protector-strong switch is causing unfortunate side-effects which prevents establishing a L2TP/IPSec connection. I've also noticed other side-effects like stray xl2tpd processes staying around. I'm still investigating and will report the bug upstream.

**Comment by Frozen-byte** [comment] 2016-06-11 11:05
any updates for xenial xerus l2tp/ipsec support?

**Comment by dkosovic** [comment] 2016-06-11 13:07
I wasn't able to reproduce the libsecret "Secret Service" not being ready after a reboot issue in this thread with qemu-kvm 2.5, possibly because I tested with a newer version of qemu-kvm. Previous network-manager-l2tp versions weren't using libsecret, but the superseded GNOME Keyring.

To get L2TP/IPec working, try building xl2tp from source code, see issue https://github.com/nm-l2tp/network-manager-l2tp/issues/6 on how to.

I don't believe the xl2tp issue I mentioned previously was an issue with fstack-protector-strong switch, as I didn't have the same results on another computer.

**Comment by Frozen-byte** [comment] 2016-06-11 16:47
Of course i built xl2tp and network-manager-l2tp (both from master branch)
I had to apply:
`apparmor_parser -R /etc/apparmor.d/usr.lib.ipsec.charon`
`apparmor_parser -R /etc/apparmor.d/usr.lib.ipsec.stroke`
So my IPsec is working correctly.
Still getting error message:
_received NO_PROPOSAL_CHOSEN error_
and 
_WARNING **: Looks like pppd didn't initialize our dbus module_

I am willing to provide any logs you need.

**Comment by dkosovic** [comment] 2016-06-12 01:52
Could you submit a new issue. I've changed the title of this issue and will close it, if it is reproduced, will reopen it. 

The issue you are seeing is with strongSwan not being able to negotiate a IPsec IKEv1 proposal with your VPN server (possible due to the configuration options supplied to strongSwan by network-manager-l2tp).  Could you install the ike-scan package and run it like so:
````sh
$ ike-scan vpn.mydomain.com 
Starting ike-scan 1.9 with 1 hosts (http://www.nta-monitor.com/tools/ike-scan/) 
123.54.76.8  Main Mode Handshake returned HDR=(CKY-R=[Available On Request]) SA=(Enc=3DES Hash=SHA1 Group=2:modp1024 Auth=PSK LifeType=Seconds LifeDuration=28800) 
VID=[Available On Request] (IKE Fragmentation)

Ending ike-scan 1.9: 1 hosts scanned in 0.037 seconds (27.14 hosts/sec).  1 returned handshake; 0 returned notify
````
But change the IP address in the output if you don't want to make it public.

**Closed** 2016-06-12 01:52 UTC
