### ISSUE TITLE
L2TP not showing in centos

### ISSUE THREAD

**Issue by bilak** [nm-l2tp/network-manager-l2tp#68] opened 2017-10-06 19:52 UTC
Hello,
I've recnetly installed `NetworkManager-l2tp-1.2.8-1.el7` but unfortunatelly I can't see the configuration in settings VPN tab. I also tried to build sources manually but that didn't solved the issue. Centos release is `CentOS Linux release 7.4.1708 (Core)`. If I can help you somehow trace the problem let me know.

**Comment by dkosovic** [comment] 2017-10-07 02:20
Which desktop environment are you using? e.g. GNOME, GNOME Classic, MATE, Cinnamon, etc? I'm not able to reproduce with GNOME and CentoOS 7.4.1708. I think the default CentOS 7 desktop is GNOME Classic. If you are using a desktop environment other than KDE, I assume you also have `NetworkManager-l2tp-gnome-1.2.8-1.el7` installed.

Are you able to do VPN configurations if you run `/usr/bin/nm-connection-editor` directly?

**Comment by bilak** [comment] 2017-10-07 08:43
Hi, I'm using KDE. After installation of NetworkManager-l2tp-gnome when I run `/usr/bin/nm-connection-editor` I'm able to setup vpn, but is there way how to enable l2tp setup in default KDE NetworkManager?

**Comment by dkosovic** [comment] 2017-10-07 09:33
This github repo doesn't provide the KDE GUI frontend for NetworkManager-l2tp. The KDE L2TP GUI is part of KDE's `plasma-nm` :
* https://cgit.kde.org/plasma-nm.git

in particular the L2TP code is located here:
* https://cgit.kde.org/plasma-nm.git/tree/vpn/l2tp

With EPEL7, I notice it includes the following KDE VPN RPMs which were built in 2014 using code from the same year :
* kde-plasma-networkmanagement-openconnect-0.9.0.9-3.el7
* kde-plasma-networkmanagement-openvpn.-0.9.0.9-3.el7
* kde-plasma-networkmanagement-vpnc-0.9.0.9-3.el7

they were build from `kde-plasma-networkmanagement-0.9.0.9-7.el7.src.rpm` and uses source code from the following GIT repo :
* https://cgit.kde.org/networkmanagement.git

unlike the newer `pasma-nm` GIT repo, it has no L2TP frontend:
* https://cgit.kde.org/networkmanagement.git/tree/vpnplugins

Sorry I'm not sure how you are supposed to get newer KDE RPMs for CentOS 7.

**Comment by bilak** [comment] 2017-10-07 09:44
ok nevermind, I just switched to GNOME. Thank you.

**Comment by dkosovic** [comment] 2017-10-07 09:48
I'll close this issue.

EPEL 7 would need to change to `plasma-nm` which Fedora changed to 4 years ago :
* https://fedoraproject.org/wiki/Changes/Plasma-nm
In theory you could build `plasma-nm` RPMs from the Fedora source RPMs.

**Closed by dkosovic** 2017-10-07 09:48 UTC
